version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/data_infra_homelab_rpi/traefik/dynamic:/dynamic:ro
      - /opt/data_infra_homelab_rpi/traefik/certs:/certs:ro
    networks:
      - proxy_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - proxy_net
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    # Persist config
    volumes:
      - /opt/infra_homelab_rpi/homelab-proxy/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      - TZ=Europe/Prague
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_HOST}
    #  - HOMEPAGE_ALLOWED_HOSTS=home.ucimse.lol,home.ucimse.lol:443
    networks:
      - proxy_net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${HOMEPAGE_HOST}`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      # - "traefik.http.routers.homepage.tls.certresolver=le"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - homepage.group=Infrastructure
      - homepage.name=Homepage
      - homepage.icon=homepage
      - homepage.href=${HOMEPAGE_URL}
      - homepage.description=Home dashboard


networks:
  proxy_net:
    external: true
