- Dashboard:
    - Homepage:
        href: {{HOMEPAGE_URL}}
        description: Homelab start page
        icon: homepage
    - Portainer:
        href: {{HOMEPAGE_PORTAINER_URL}}
        description: Container management
        icon: portainer

- Personal:
    - Actual Budget:
        href: {{HOMEPAGE_ACTUAL_BUDGET_URL}}
        description: Budget
        icon: actualbudget
    - Habit Tracker:
        href: {{HOMEPAGE_HABITS_URL}}
        description: Habits

- Media:
    - Jellyfin:
        href: {{HOMEPAGE_JELLYFIN_URL}}
        description: Media server
        icon: jellyfin

- Arr Stack:
    - Radarr:
        href: {{HOMEPAGE_RADARR_URL}}
        icon: radarr
    - Sonarr:
        href: {{HOMEPAGE_SONARR_URL}}
        icon: sonarr
    - Prowlarr:
        href: {{HOMEPAGE_PROWLARR_URL}}
        icon: prowlarr
    - Bazarr:
        href: {{HOMEPAGE_BAZARR_URL}}
        icon: bazarr
    - Lidarr:
        href: {{HOMEPAGE_LIDARR_URL}}
        icon: lidarr

- Downloads:
    - SABnzbd:
        href: {{HOMEPAGE_SABNZBD_URL}}
        icon: sabnzbd
    - qBittorrent:
        href: {{HOMEPAGE_QBITTORRENT_URL}}
        icon: qbittorrent
