- Dashboard:
    - Homepage:
        href: ${HOMEPAGE_URL}
        description: Homelab start page
        icon: homepage
    - Portainer:
        href: ${PORTAINER_URL}
        description: Container management
        icon: portainer

- Personal:
    - Actual Budget:
        href: ${ACTUAL_BUDGET_URL}
        description: Budget
        icon: actualbudget
    - Habit Tracker:
        href: ${HABITS_URL}
        description: Habits

- Media:
    - Jellyfin:
        href: ${JELLYFIN_URL}
        description: Media server
        icon: jellyfin

- Arr Stack:
    - Radarr:
        href: ${RADARR_URL}
        icon: radarr
    - Sonarr:
        href: ${SONARR_URL}
        icon: sonarr
    - Prowlarr:
        href: ${PROWLARR_URL}
        icon: prowlarr
    - Bazarr:
        href: ${BAZARR_URL}
        icon: bazarr
    - Lidarr:
        href: ${LIDARR_URL}
        icon: lidarr

- Downloads:
    - SABnzbd:
        href: ${SABNZBD_URL}
        icon: sabnzbd
    - qBittorrent:
        href: ${QBITTORRENT_URL}
        icon: qbittorrent
