---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Homelab
headerStyle: boxed
theme: dark
color: slate
hideVersion: true

providers:
  openweathermap: ${OPENWEATHERMAP_API_KEY}
  weatherapi: ${WEATHERAPI_API_KEY}
