services:
  # jellyfin is used to serve your media to the client devices
  jellyfin:
    image: lscr.io/linuxserver/${MEDIA_SERVICE}
    container_name: ${MEDIA_SERVICE}
    #network_mode: host # plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/${MEDIA_SERVICE}:/config
    ports:
      - ${JELLYFIN_PORT:-8096}:8096
    restart: unless-stopped
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin
      - homepage.href=${HOMEPAGE_JELLYFIN_URL}
      - homepage.description=Media server

  # qBitorrent is used to download torrents
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.3
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/qbittorrent:/config
    restart: unless-stopped
    #ports: # qbittorrent
      #- 8081:8081 # qbittorrent
    network_mode: "service:gluetun"
    labels:
      - homepage.group=Downloads
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent
      - homepage.href=${HOMEPAGE_QBITTORRENT_URL}
      - homepage.description=Torrent client

  # SABnzbd is used to download from usenet
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Montevideo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/sabnzbd:/config
    #ports: # sabnzbd
      #- 8080:8080 # sabnzbd
    restart: unless-stopped
    network_mode: "service:gluetun"
    labels:
      - homepage.group=Downloads
      - homepage.name=SABnzbd
      - homepage.icon=sabnzbd
      - homepage.href=${HOMEPAGE_SABNZBD_URL}
      - homepage.description=Usenet client

  # Sonarr is used to query, add downloads to the download queue and index TV shows
  # https://sonarr.tv/
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/sonarr:/config
    ports:
      - ${SONARR_PORT:-8989}:8989
    restart: unless-stopped
    networks:
      yams_network:
        ipv4_address: 172.60.0.13
    labels:
      - homepage.group=Automation
      - homepage.name=Sonarr
      - homepage.icon=sonarr
      - homepage.href=${HOMEPAGE_SONARR_URL}
      - homepage.description=TV automation

  # Radarr is used to query, add downloads to the download queue and index Movies
  # https://radarr.video/
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/radarr:/config
    ports:
      - ${RADARR_PORT:-7878}:7878
    restart: unless-stopped
    networks:
      yams_network:
        ipv4_address: 172.60.0.14
    labels:
      - homepage.group=Automation
      - homepage.name=Radarr
      - homepage.icon=radarr
      - homepage.href=${HOMEPAGE_RADARR_URL}
      - homepage.description=Movie automation

  # Lidarr is used to query, add downloads to the download queue and index Music
  # https://lidarr.audio/
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/lidarr:/config
    ports:
      - ${LIDARR_PORT:-8686}:8686
    restart: unless-stopped
    networks:
      yams_network:
        ipv4_address: 172.60.0.15
    labels:
      - homepage.group=Automation
      - homepage.name=Lidarr
      - homepage.icon=lidarr
      - homepage.href=${HOMEPAGE_LIDARR_URL}
      - homepage.description=Music automation

  # Bazarr is used to download and categorize subtitles
  # https://www.bazarr.media/
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIA_DIRECTORY}:/data
      - ${INSTALL_DIRECTORY}/bazarr:/config
    ports:
      - ${BAZARR_PORT:-6767}:6767
    restart: unless-stopped
    networks:
      yams_network:
        ipv4_address: 172.60.0.16
    labels:
      - homepage.group=Automation
      - homepage.name=Bazarr
      - homepage.icon=bazarr
      - homepage.href=${HOMEPAGE_BAZARR_URL}
      - homepage.description=Subtitle automation

  # Prowlarr is our torrent indexer/searcher. Sonarr/Radarr use Prowlarr as a source
  # https://prowlarr.com/
  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${INSTALL_DIRECTORY}/prowlarr:/config
    ports:
      - ${PROWLARR_PORT:-9696}:9696
    restart: unless-stopped
    networks:
      yams_network:
        ipv4_address: 172.60.0.17
    labels:
      - homepage.group=Automation
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr
      - homepage.href=${HOMEPAGE_PROWLARR_URL}
      - homepage.description=Indexer manager

  # Gluetun is our VPN, so you can download torrents safely
  gluetun:
    image: qmcgaw/gluetun:v3.40.3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${GLUETUN_HTTP_PROXY_PORT:-8888}:8888/tcp # HTTP proxy
      - ${GLUETUN_SHADOWSOCKS_TCP_PORT:-8388}:8388/tcp # Shadowsocks
      - ${GLUETUN_SHADOWSOCKS_UDP_PORT:-8388}:8388/udp # Shadowsocks
      - ${GLUETUN_ADMIN_PORT:-8003}:8000/tcp # Admin
      - ${GLUETUN_CONTROL_PORT:-8080}:8080/tcp # gluetun
      - ${GLUETUN_QBITTORRENT_PORT:-8081}:8081/tcp # gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_CIPHERS=AES-256-GCM
      # uz je dole - PORT_FORWARD_ONLY=off
      #- VPN_PORT_FORWARDING=off
      - DNS_ADDRESS=127.0.0.11
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS}
#      - FREE_ONLY=on
      - FIREWALL_INPUT_PORTS=${FIREWALL_INPUT_PORTS}
      - PORT_FORWARD_ONLY=on
#      - FIREWALL_VPN_INPUT_PORTS=1024-65535
      #- FIREWALL_VPN_INPUT_PORTS=42055
      - VPN_PORT_FORWARDING=on
#      - FIREWALL_OUTBOUND_SUBNETS=172.60.0.0/24
    restart: unless-stopped
    networks:
      yams_network:
        ipv4_address: 172.60.0.18
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Gluetun
      - homepage.icon=gluetun
      - homepage.href=${HOMEPAGE_GLUETUN_URL}
      - homepage.description=VPN gateway

  # Portainer helps debugging and monitors the containers
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - ${PORTAINER_PORT:-9000}:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${INSTALL_DIRECTORY}/portainer:/data
    restart: unless-stopped
    networks:
      yams_network:
        ipv4_address: 172.60.0.19
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Portainer
      - homepage.icon=portainer
      - homepage.href=${HOMEPAGE_PORTAINER_URL}
      - homepage.description=Docker management

  # Watchtower is going to keep our instances updated
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      yams_network:
        ipv4_address: 172.60.0.20
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Watchtower
      - homepage.icon=watchtower
      - homepage.description=Auto updates

networks:
  yams_network:
    name: yams_network
    ipam:
      config:
        - subnet: ${YAMS_SUBNET}
